repos:
  - repo: https://github.com/Quantco/pre-commit-mirrors-black
    rev: 23.7.0
    hooks:
      - id: black-conda
        args:
          - --safe
          - --target-version=py38
  - repo: https://github.com/Quantco/pre-commit-mirrors-flake8
    rev: 6.1.0
    hooks:
      - id: flake8-conda
        additional_dependencies: [
          -c,
          conda-forge,
          flake8-bugbear,
          flake8-builtins,
          flake8-comprehensions,
          flake8-docstrings,
          flake8-rst-docstrings,
          flake8-print,
          pep8-naming,
        ]
  - repo: https://github.com/Quantco/pre-commit-mirrors-isort
    rev: 5.12.0
    hooks:
      - id: isort-conda
        additional_dependencies: [-c, conda-forge, toml=0.10.2]
  - repo: https://github.com/Quantco/pre-commit-mirrors-mypy
    rev: "1.5.1"
    hooks:
      - id: mypy-conda
        additional_dependencies: [-c, conda-forge, types-setuptools]
  - repo: https://github.com/Quantco/pre-commit-mirrors-pyupgrade
    rev: 3.10.1
    hooks:
      - id: pyupgrade-conda
        args:
          - --py38-plus
  - repo: https://github.com/Quantco/pre-commit-mirrors-prettier
    rev: 3.0.2
    hooks:
      - id: prettier-conda
        files: "\\.md$"
  - repo: https://github.com/Quantco/pre-commit-mirrors-pre-commit-hooks
    rev: 4.4.0
    hooks:
      - id: end-of-file-fixer-conda
      - id: trailing-whitespace-conda
      - id: mixed-line-ending-conda
