[tool.black]
exclude = '''
/(
    \.eggs
  | \.git
  | \.venv
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
ensure_newline_before_comments = true
line_length = 88
default_section = 'THIRDPARTY'

[tool.mypy]
python_version = 3.10
ignore_missing_imports = true
no_implicit_optional = true
check_untyped_defs = true
explicit_package_bases = true
